workspace:
  base: /go
  path: src/github.com/stefanhans/Go4Drone-Apps
clone:
  git:
    image: plugins/git
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build -o ./drone-app
      - ls -la drone-app
  publish:
    image: plugins/docker
    repo: stefanhans/drone-app
    tags: 1.0.5
    secrets: [ docker_username, docker_password ]

