workspace:
  base: /go
  path: src/github.com/stefanhans/Go4Drone-Apps
clone:
  git:
    image: plugins/git
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build -o ./drone-app
      - pwd
      - ls -la .
  publish:
    image: plugins/docker
    registry: hub.docker.com
    repo: hub.docker.com/r/stefanhans/drone-app

